---
name: 'Python Publish'


on:
  workflow_call:
    inputs:
      PYTHON_PROJECT_NAME:
        description: PyPi Package Project
        required: true
        type: string

      PYTHON_PROJECT_URL:
        description: PyPi Package Project
        default: pypi.org    # pypi.org | test.pypi.org 
        required: false
        type: string

    # secrets:
    #   password:
    #     required: true

jobs:


  pypi-publish:
    name: Upload release to PyPI
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://${{ inputs.PYTHON_PROJECT_URL}}/p/${{ inputs.PYTHON_PROJECT_NAME}}/
    permissions:
      id-token: write
    steps:

      - name: Download built artifact to dist/
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c    # V8.0.1
        with:
          name: Packages
          path: dist


      # - name: Publish package distributions to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     skip-existing: true
      #     repository-url: https://${{ inputs.PYTHON_PROJECT_URL}}/project/${{ inputs.PYTHON_PROJECT_NAME}}/
      #     user: ${{ secrets.NFC_PYPI_USERNAME }}
      #     password: ${{ secrets.NFC_PYPI_TOKEN }}


      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97    # v7.0.0
        with:
          python-version: '3.13'


      - name: Install Twine
        run: |
          pip install twine


      - name: Trace
        run: |
          ls -l;
          echo '****************************************************';
          ls -l dist/;


      - name: Publish package distributions to PyPI
        # env:
        #   TWINE_USERNAME: __token__
        #   TWINE_PASSWORD: ${{ secrets.NFC_PYPI_TOKEN }}
        #   TWINE_REPOSITORY: https://${{ inputs.PYTHON_PROJECT_URL}}/project/${{ inputs.PYTHON_PROJECT_NAME}}/
        run: |
          twine upload \
            --verbose \
            --username __token__ \
            --password ${{ secrets.NFC_PYPI_TOKEN }} \
            dist/*
